name: Generate Snake

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"  # Every day at midnight

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # 👈 IMPORTANT: allows pushing to another branch

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Generate the snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: debjit11
          outputs: dist/github-contribution-grid-snake.svg

      - name: Push the generated snake to the output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
