name: Generate Snake

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"  # every day at midnight

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Generate the snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: debjit11
          outputs: dist/github-contribution-grid-snake.svg
          color_snake: "#00FF00"  # bright green snake
          color_dots: "#161B22,#0D1117,#161B22,#39D353,#39D353"  # GitHub dark green + dark grid

      - name: Push the generated snake to the output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

